#!/bin/bash
cd 0x03-shell_expansions
julien@ubuntu:/tmp/0x03$ ls 0-alias file 1 file 2
julien@ubuntu:/tmp/0x03$ source ./0-alias
julien@ubuntu:/tmp/0x03$ ls
julien@ubuntu:/tmp/0x03$ /ls
julien@ubuntu:/tmp/0x03$
